### ISSUE TITLE
Problems with own properties on Neos.Neos:Content

### ISSUE THREAD

**Issue by patriceckhart** [neos/form-builder#31]
Since updating to Neos 4 I get the following error, when I insert an email validator: 
Unsupported validation option (s) found: animation, delay, mt, mb, ml, mr. 

I use these properties for Neos.Neos:Content. I'm not sure why the validators implement Neos.Neos:Content.

**Comment by bwaidelich** [comment]
I checked again and Validators have `Neos.Neos:Content` as superType so that they appear in the Neos Backend.
The issue occurs in the [NodeBasedValidator implementation](https://github.com/neos/form-builder/blob/master/Resources/Private/Fusion/NodeBased/NodeBasedValidator.fusion#L4) that translates all node properties to options of the validator..
We should change that so that the options have to be defined in the corresponding `*.Definition` of the validator

**Comment by patriceckhart** [comment]
Is there already a temporary solution?

**Comment by patriceckhart** [comment]
I have created an own content NodeType like NeosRulez.Bootstrap:Content with supertype Neos.Neos:Content and it works.

**Comment by patriceckhart** [comment]
I have changed to line 
`options.@process.addNodeProperties = ${Array.concat(value, validatorNode.properties)}`
in Private/Resources/Fusion/NodeBased/NodeBasedValidator.fusion to
`options >`
and it works. The validators also.

**Comment by EnesE** [comment]
> I have changed to line
> 
> `options.@process.addNodeProperties = ${Array.concat(value, validatorNode.properties)}`
> 
> in Private/Resources/Fusion/NodeBased/NodeBasedValidator.fusion to
> `options >`
> 
> and it works. The validators also.

You can fix it like this too:

```
'Neos.Form.Builder:AbstractValidator':
  properties:
    # Remove `marginTop` and` marginBottom` as they cause an error and don't work here anyway
    marginTop: FALSE
    marginBottom: FALSE
    ## your other options
```
